[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ran-tldr"
version = "0.1.0"
requires-python = ">=3.7"

[project.scripts]
ran-tldr = "tldr:tldr"

[tool.setuptools]
py-modules = ["tldr"]
